site_name: Documentation
theme:
  name: material

  nav:  
   - Home: index.md  
   - Git: git.md    
   - Visual Studio Code: vs_code.md  
   - Github: github.md  
   - Start your repo: start_repo.md
