site_name: Documentation  
theme:  
  name: material  

nav:  
  - Home: index.md  
  - Git: git.md    
  - Visual Studio Code: vs-code.md  
  - Github: github.md  
  - Start your repository: start-repository.md
  